@startuml
class Utilisateur {
    - id : int
    - pseudo : String
    - motDePasse : String
    - estAuthentifie : boolean
    - Todolist : todolist
    + creerCompte(pseudo : String, motDePasse : String) : Utilisateur (service)
    + seConnecter(pseudo : String, motDePasse : String) : Utilisateur (service)
    + seDeconnecter() : void

}

class TodoList {
    - id : int
    - taches : List<Tache>
    - User : user
    + getTodoList() : TodoList (service)
    + ajouterTache(tache : Tache) : void
    + supprimerTache(tache : Tache) : void
    + getTachesParCategorie(categorie : String) : List<Tache> (service)
}

class Tache {
    - id : int
    - titre : String
    - description : String
    - dateLimite : Date
    - statut : Statut
    - categorie : String
    + completerTache() : void
    + modifierTache(titre : String, description : String, dateLimite : Date, statut : Statut) : void
}

enum Statut {
    A_FAIRE
    EN_COURS
    TERMINEE
}

Utilisateur "0" --> "1" TodoList : possède
TodoList "1" --> "1" Utilisateur : appartient à
TodoList "0" --> "N" Tache : contient
Tache "1" --> "1" TodoList : appartient à

@enduml
